apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-manager
    service-type: config_manager
  name: config-manager-service
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8084
  selector:
    app: config-manager
  type: ClusterIP
