apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator
    service-type: orchestrator
  name: orchestrator-service
  namespace: staging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: orchestrator
  type: ClusterIP
