"""add_agent_action_log

Revision ID: 6540e6ee8ea8
Revises: 86628f03fb5e
Create Date: 2026-04-19 01:18:36.222386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6540e6ee8ea8'
down_revision: Union[str, None] = '86628f03fb5e'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
