"""v1_baseline

Revision ID: 86628f03fb5e
Revises: 006
Create Date: 2026-04-19 01:02:10.100600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86628f03fb5e'
down_revision: Union[str, None] = '006'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sso_configurations')
    op.drop_index('ix_event_log_event_type', table_name='event_logs')
    op.drop_index('ix_event_log_org_ts', table_name='event_logs')
    op.drop_index('ix_event_log_user_ts', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_table('pricing_plans')
    op.drop_index('ix_email_verif_user', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('ix_sso_users_org_id', table_name='sso_users')
    op.drop_index('ix_sso_users_user_id', table_name='sso_users')
    op.drop_table('sso_users')
    op.drop_table('support_tickets')
    op.create_index(op.f('ix_agents_owner_user_id'), 'agents', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'agents', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_alert_records_owner_user_id'), 'alert_records', ['owner_user_id'], unique=False)
    op.create_foreign_key(None, 'alert_records', 'users', ['owner_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('audit_logs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'action_type')
    op.drop_column('audit_logs', 'status')
    op.drop_column('organizations', 'service_count')
    op.drop_column('organizations', 'service_limit')
    op.drop_column('organizations', 'sso_enabled')
    op.alter_column('remediation_jobs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_remediation_jobs_created_at'), 'remediation_jobs', ['created_at'], unique=False)
    op.alter_column('users', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('users', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_remediation_jobs_created_at'), table_name='remediation_jobs')
    op.alter_column('remediation_jobs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('organizations', sa.Column('sso_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('organizations', sa.Column('service_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('service_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('audit_logs', 'org_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'alert_records', type_='foreignkey')
    op.drop_index(op.f('ix_alert_records_owner_user_id'), table_name='alert_records')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_owner_user_id'), table_name='agents')
    op.create_table('support_tickets',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='support_tickets_org_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='support_tickets_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='support_tickets_pkey')
    )
    op.create_table('sso_users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('saml_name_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sso_only', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_saml_auth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='sso_users_org_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sso_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sso_users_pkey'),
    sa.UniqueConstraint('saml_name_id', name='sso_users_saml_name_id_key')
    )
    op.create_index('ix_sso_users_user_id', 'sso_users', ['user_id'], unique=False)
    op.create_index('ix_sso_users_org_id', 'sso_users', ['org_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='email_verification_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='email_verification_tokens_pkey'),
    sa.UniqueConstraint('token_hash', name='email_verification_tokens_token_hash_key')
    )
    op.create_index('ix_email_verif_user', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('service_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sso_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('api_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pricing_plans_pkey'),
    sa.UniqueConstraint('name', name='pricing_plans_name_key')
    )
    op.create_table('event_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='event_logs_org_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_logs_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='event_logs_pkey')
    )
    op.create_index('ix_event_log_user_ts', 'event_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_event_log_org_ts', 'event_logs', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_event_log_event_type', 'event_logs', ['event_type'], unique=False)
    op.create_table('sso_configurations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('idp_provider', sa.VARCHAR(length=30), server_default=sa.text("'okta'::character varying"), autoincrement=False, nullable=False),
    sa.Column('metadata_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entity_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acs_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('x509_cert', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name='sso_configurations_org_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sso_configurations_pkey'),
    sa.UniqueConstraint('org_id', name='sso_configurations_org_id_key')
    )
    # ### end Alembic commands ###
