apiVersion: v1
kind: Service
metadata:
  labels:
    app: analytics-engine
    service-type: analytics_engine
  name: analytics-engine-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8083
  selector:
    app: analytics-engine
  type: ClusterIP
