apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
    service-type: api_gateway
  name: api-gateway-service
  namespace: production
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  type: ClusterIP
